# api/crypto_utils.py
from __future__ import annotations

import os
from cryptography.fernet import Fernet
from fastapi import HTTPException

# This must be a Fernet key (base64 urlsafe 32 bytes), e.g. generated by Fernet.generate_key()
INTEGRATIONS_ENC_KEY = os.getenv("INTEGRATIONS_ENC_KEY", "").strip()


def _fernet() -> Fernet:
    if not INTEGRATIONS_ENC_KEY:
        raise HTTPException(status_code=500, detail="INTEGRATIONS_ENC_KEY is missing")
    key: bytes = INTEGRATIONS_ENC_KEY.encode("utf-8")
    return Fernet(key)


def encrypt_secret(value: str | None) -> str | None:
    if not value:
        return None
    f = _fernet()
    return f.encrypt(value.encode("utf-8")).decode("utf-8")


def decrypt_secret(token: str | None) -> str | None:
    if not token:
        return None
    f = _fernet()
    return f.decrypt(token.encode("utf-8")).decode("utf-8")
