# pytest.ini
[pytest]
filterwarnings =
    ignore:The `gotrue` package is deprecated:DeprecationWarning
minversion = 8.0

pythonpath = src

testpaths =
    src/data_scout/fetchers/tests
    src/data_scout/indicators/tests

addopts =
    --cov=src/data_scout
    --cov-report=term-missing
    --cov-fail-under=70
