# pytest.ini
[pytest]
minversion = 8.0

pythonpath = src

testpaths =
    src/data_scout/fetchers/tests
    src/data_scout/indicators/tests
    src/data_scout/data_layer/tests

addopts =
    --cov=src/data_scout
    --cov-report=term-missing
    --cov-fail-under=70
    -ra -m "not slow"

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')