# pytest.ini
[pytest]
minversion = 8.0

# Where your tests live
testpaths =
    src/data_scout/tests

# Global options applied every time you run `pytest`
addopts =
    --cov=src/data_scout
    --cov-report=term-missing
    --cov-fail-under=70
